<?php

namespace Database\Seeders;

use App\Models\JobPosting;
use App\Models\MedicalInstitution;
use App\Models\Specialty;
use Illuminate\Database\Seeder;

class JobPostingSeeder extends Seeder
{
    public function run(): void
    {
        $recruiter = MedicalInstitution::withoutGlobalScopes()
            ->where('email', 'recruiter@vaidyog.com')
            ->first();

        if (!$recruiter) {
            $this->command->warn('Recruiter not found. Run RecruiterSeeder first.');
            return;
        }

        // Delete existing seeded jobs for this recruiter
        JobPosting::where('recruiter_id', $recruiter->id)->forceDelete();

        $specialties = Specialty::pluck('id', 'slug');

        $jobs = [
            // ── Featured jobs ──────────────────────────────────────────
            [
                'job_title'                  => 'Senior Cardiologist',
                'institution_name'           => 'City Hospital',
                'specialty_slug'             => 'cardiology',
                'employment_type'            => 'full_time',
                'location_city'              => 'Mumbai',
                'location_state'             => 'Maharashtra',
                'experience_min'             => 5,
                'experience_max'             => 15,
                'salary_min'                 => 2500000,
                'salary_max'                 => 4500000,
                'key_skills'                 => ['Clinical Assessment', 'ECG Interpretation', 'Critical Care', 'ACLS', 'Patient Care'],
                'educational_requirements'   => ['MBBS', 'MD', 'DM (Super Specialty)'],
                'medical_qualifications'     => ['MBBS', 'MD (Medicine)', 'DM (Cardiology)'],
                'certifications_required'    => ['ACLS (Advanced Cardiac Life Support)', 'Medical Council Registration (MCI/NMC)'],
                'description'                => 'We are looking for an experienced Cardiologist to join our cardiac sciences department. The ideal candidate will have hands-on experience with interventional procedures and a strong clinical background.',
                'vacancies'                  => 2,
                'is_featured'                => true,
                'category_slug'              => 'doctors',
                'subcategory_name'           => 'Cardiologist',
            ],
            [
                'job_title'                  => 'ICU Staff Nurse',
                'institution_name'           => 'City Hospital',
                'specialty_slug'             => 'nursing-professionals',
                'employment_type'            => 'full_time',
                'location_city'              => 'New Delhi',
                'location_state'             => 'Delhi',
                'experience_min'             => 2,
                'experience_max'             => 6,
                'salary_min'                 => 400000,
                'salary_max'                 => 700000,
                'key_skills'                 => ['Critical Care', 'Ventilator Management', 'CPR / BLS', 'Vital Signs Monitoring', 'IV Administration'],
                'educational_requirements'   => ['B.Sc Nursing', 'GNM (General Nursing & Midwifery)'],
                'medical_qualifications'     => ['B.Sc Nursing'],
                'certifications_required'    => ['BLS (Basic Life Support)', 'Nursing Council Registration', 'Critical Care Nursing Certificate'],
                'description'                => 'Seeking a dedicated ICU Nurse with experience in critical care units. Must be skilled in ventilator management and emergency protocols.',
                'vacancies'                  => 5,
                'is_featured'                => true,
                'category_slug'              => 'nursing',
                'subcategory_name'           => 'ICU Nurse',
            ],
            [
                'job_title'                  => 'Consultant Orthopaedic Surgeon',
                'institution_name'           => 'City Hospital',
                'specialty_slug'             => 'orthopaedics',
                'employment_type'            => 'full_time',
                'location_city'              => 'Bengaluru',
                'location_state'             => 'Karnataka',
                'experience_min'             => 8,
                'experience_max'             => 20,
                'salary_min'                 => 3000000,
                'salary_max'                 => 5500000,
                'key_skills'                 => ['Surgical Assistance', 'Operating Room Protocol', 'Rehabilitation Therapy', 'Patient Care'],
                'educational_requirements'   => ['MBBS', 'MS (Surgery)', 'DNB'],
                'medical_qualifications'     => ['MBBS', 'MS (Orthopedics)', 'DNB (Various Specialties)'],
                'certifications_required'    => ['Medical Council Registration (MCI/NMC)', 'ATLS (Advanced Trauma Life Support)'],
                'description'                => 'Leading multi-specialty hospital looking for a Consultant Orthopaedic Surgeon with expertise in joint replacement and arthroscopic procedures.',
                'vacancies'                  => 1,
                'is_featured'                => true,
                'category_slug'              => 'doctors',
                'subcategory_name'           => 'Orthopedic Surgeon',
            ],
            [
                'job_title'                  => 'Clinical Pharmacist',
                'institution_name'           => 'City Hospital',
                'specialty_slug'             => 'pharmacy',
                'employment_type'            => 'full_time',
                'location_city'              => 'Hyderabad',
                'location_state'             => 'Telangana',
                'experience_min'             => 1,
                'experience_max'             => 5,
                'salary_min'                 => 350000,
                'salary_max'                 => 600000,
                'key_skills'                 => ['Pharmacology', 'Patient Counseling', 'Quality Assurance', 'Compliance & Regulatory'],
                'educational_requirements'   => ['B.Pharm', 'M.Pharm'],
                'medical_qualifications'     => ['B.Pharm', 'M.Pharm'],
                'certifications_required'    => ['Pharmacy Council Registration', 'Good Clinical Practice (GCP)'],
                'description'                => 'Seeking a Clinical Pharmacist to manage drug dispensing, support clinical trials, and provide patient medication counselling.',
                'vacancies'                  => 3,
                'is_featured'                => true,
                'category_slug'              => 'pharmacy',
                'subcategory_name'           => 'Clinical Pharmacist',
            ],
            [
                'job_title'                  => 'Radiologist – MRI & CT Specialist',
                'institution_name'           => 'City Hospital',
                'specialty_slug'             => 'radiology-imaging',
                'employment_type'            => 'full_time',
                'location_city'              => 'Chennai',
                'location_state'             => 'Tamil Nadu',
                'experience_min'             => 3,
                'experience_max'             => 10,
                'salary_min'                 => 1800000,
                'salary_max'                 => 3200000,
                'key_skills'                 => ['Diagnostic Imaging', 'MRI Interpretation', 'Radiology', 'Ultrasound'],
                'educational_requirements'   => ['MBBS', 'MD'],
                'medical_qualifications'     => ['MBBS', 'MD (Radiology)'],
                'certifications_required'    => ['Medical Council Registration (MCI/NMC)', 'Radiography License'],
                'description'                => 'We need a Radiologist with expertise in MRI and CT interpretation to join our imaging department.',
                'vacancies'                  => 2,
                'is_featured'                => true,
                'category_slug'              => 'doctors',
                'subcategory_name'           => 'Radiologist',
            ],
            [
                'job_title'                  => 'Paediatric Neurologist',
                'institution_name'           => 'City Hospital',
                'specialty_slug'             => 'neurology-neurosurgery',
                'employment_type'            => 'full_time',
                'location_city'              => 'Pune',
                'location_state'             => 'Maharashtra',
                'experience_min'             => 4,
                'experience_max'             => 12,
                'salary_min'                 => 2200000,
                'salary_max'                 => 4000000,
                'key_skills'                 => ['Clinical Assessment', 'Pediatric Care', 'Patient Counseling', 'Research & Data Analysis'],
                'educational_requirements'   => ['MBBS', 'MD', 'DM (Super Specialty)'],
                'medical_qualifications'     => ['MBBS', 'MD (Pediatrics)', 'DM (Neurology)'],
                'certifications_required'    => ['Medical Council Registration (MCI/NMC)', 'PALS (Pediatric Advanced Life Support)'],
                'description'                => 'City Hospital Pune is looking for a Paediatric Neurologist specializing in epilepsy management and neuro-developmental disorders.',
                'vacancies'                  => 1,
                'is_featured'                => true,
                'category_slug'              => 'doctors',
                'subcategory_name'           => 'Neurologist',
            ],

            // ── Regular (non-featured) jobs ────────────────────────────
            [
                'job_title'                  => 'Physiotherapist',
                'institution_name'           => 'City Hospital',
                'specialty_slug'             => 'physiotherapy',
                'employment_type'            => 'full_time',
                'location_city'              => 'Jaipur',
                'location_state'             => 'Rajasthan',
                'experience_min'             => 1,
                'experience_max'             => 4,
                'salary_min'                 => 300000,
                'salary_max'                 => 500000,
                'key_skills'                 => ['Rehabilitation Therapy', 'Physiotherapy Techniques', 'Patient Care', 'Medical Equipment Handling'],
                'educational_requirements'   => ['BPT (Physiotherapy)', 'MPT (Physiotherapy)'],
                'medical_qualifications'     => ['BPT'],
                'certifications_required'    => ['State Medical Council Registration'],
                'description'                => 'Looking for a qualified Physiotherapist for our rehabilitation unit specialising in musculoskeletal conditions.',
                'vacancies'                  => 2,
                'is_featured'                => false,
                'category_slug'              => 'allied-health',
                'subcategory_name'           => 'Physiotherapist',
            ],
            [
                'job_title'                  => 'Dental Surgeon',
                'institution_name'           => 'City Hospital',
                'specialty_slug'             => 'dental-professionals',
                'employment_type'            => 'full_time',
                'location_city'              => 'Ahmedabad',
                'location_state'             => 'Gujarat',
                'experience_min'             => 2,
                'experience_max'             => 7,
                'salary_min'                 => 600000,
                'salary_max'                 => 1200000,
                'key_skills'                 => ['Surgical Assistance', 'Patient Care', 'Medical Equipment Handling'],
                'educational_requirements'   => ['BDS', 'MDS'],
                'medical_qualifications'     => ['BDS', 'MDS (Oral Surgery)'],
                'certifications_required'    => ['Dental Council Registration'],
                'description'                => 'Experienced Dental Surgeon required for our multi-chair dental department with expertise in implantology and cosmetic procedures.',
                'vacancies'                  => 1,
                'is_featured'                => false,
                'category_slug'              => 'doctors',
                'subcategory_name'           => 'Dentist',
            ],
            [
                'job_title'                  => 'Lab Technician – Pathology',
                'institution_name'           => 'City Hospital',
                'specialty_slug'             => 'laboratory-pathology',
                'employment_type'            => 'full_time',
                'location_city'              => 'Kolkata',
                'location_state'             => 'West Bengal',
                'experience_min'             => 0,
                'experience_max'             => 3,
                'salary_min'                 => 200000,
                'salary_max'                 => 350000,
                'key_skills'                 => ['Lab Analysis', 'Phlebotomy', 'Blood Bank Management', 'Medical Equipment Handling'],
                'educational_requirements'   => ['DMLT', 'B.Sc MLT (Medical Lab Technology)'],
                'medical_qualifications'     => [],
                'certifications_required'    => ['Phlebotomy Certification'],
                'description'                => 'DMLT / B.Sc MLT graduate required for our pathology laboratory. Freshers with good academic records are welcome.',
                'vacancies'                  => 4,
                'is_featured'                => false,
                'category_slug'              => 'lab-diagnostics',
                'subcategory_name'           => 'Lab Technician',
            ],
            [
                'job_title'                  => 'Ayurveda Physician',
                'institution_name'           => 'City Hospital',
                'specialty_slug'             => 'ayurveda-ayush',
                'employment_type'            => 'full_time',
                'location_city'              => 'Lucknow',
                'location_state'             => 'Uttar Pradesh',
                'experience_min'             => 2,
                'experience_max'             => 8,
                'salary_min'                 => 400000,
                'salary_max'                 => 800000,
                'key_skills'                 => ['Patient Care', 'Health Education', 'Patient Counseling'],
                'educational_requirements'   => ['BAMS'],
                'medical_qualifications'     => ['BAMS'],
                'certifications_required'    => ['AYUSH Council Registration'],
                'description'                => 'BAMS qualified Ayurveda Physician required for our integrative medicine department.',
                'vacancies'                  => 1,
                'is_featured'                => false,
                'category_slug'              => 'ayush',
                'subcategory_name'           => 'Ayurvedic Doctor',
            ],
            [
                'job_title'                  => 'Hospital Administrator',
                'institution_name'           => 'City Hospital',
                'specialty_slug'             => 'healthcare-administration',
                'employment_type'            => 'full_time',
                'location_city'              => 'Chandigarh',
                'location_state'             => 'Chandigarh',
                'experience_min'             => 5,
                'experience_max'             => 12,
                'salary_min'                 => 800000,
                'salary_max'                 => 1500000,
                'key_skills'                 => ['Hospital Administration', 'Team Leadership', 'Quality Assurance', 'Compliance & Regulatory'],
                'educational_requirements'   => ['MBA (Hospital Administration)', 'MHA (Master of Hospital Administration)'],
                'medical_qualifications'     => [],
                'certifications_required'    => ['NABH Awareness', 'Hospital Management Certificate'],
                'description'                => 'Experienced Hospital Administrator needed to oversee daily operations, NABH compliance, and departmental coordination.',
                'vacancies'                  => 1,
                'is_featured'                => false,
                'category_slug'              => 'hospital-admin',
                'subcategory_name'           => 'Hospital Administrator',
            ],
            [
                'job_title'                  => 'Emergency Medicine Specialist',
                'institution_name'           => 'City Hospital',
                'specialty_slug'             => 'emergency-critical-care',
                'employment_type'            => 'full_time',
                'location_city'              => 'Nagpur',
                'location_state'             => 'Maharashtra',
                'experience_min'             => 3,
                'experience_max'             => 10,
                'salary_min'                 => 1500000,
                'salary_max'                 => 2800000,
                'key_skills'                 => ['Emergency Medicine', 'Critical Care', 'Triage', 'CPR / BLS', 'ACLS'],
                'educational_requirements'   => ['MBBS', 'MD'],
                'medical_qualifications'     => ['MBBS', 'MD (Medicine)'],
                'certifications_required'    => ['ACLS (Advanced Cardiac Life Support)', 'ATLS (Advanced Trauma Life Support)', 'BLS (Basic Life Support)'],
                'description'                => 'We need an Emergency Medicine Specialist to lead our 24x7 emergency department. Must be certified in ACLS and ATLS.',
                'vacancies'                  => 2,
                'is_featured'                => false,
                'category_slug'              => 'doctors',
                'subcategory_name'           => 'General Physician',
            ],
            [
                'job_title'                  => 'Clinical Psychologist',
                'institution_name'           => 'City Hospital',
                'specialty_slug'             => 'mental-health-psychology',
                'employment_type'            => 'part_time',
                'location_city'              => 'Kochi',
                'location_state'             => 'Kerala',
                'experience_min'             => 2,
                'experience_max'             => 6,
                'salary_min'                 => 300000,
                'salary_max'                 => 550000,
                'key_skills'                 => ['Mental Health Support', 'Patient Counseling', 'Communication Skills'],
                'educational_requirements'   => ['M.Sc Nursing', 'Post Graduate Diploma'],
                'medical_qualifications'     => [],
                'certifications_required'    => ['State Medical Council Registration'],
                'description'                => 'Part-time Clinical Psychologist needed for our mental wellness unit. RCI registration required.',
                'vacancies'                  => 1,
                'is_featured'                => false,
                'category_slug'              => 'allied-health',
                'subcategory_name'           => 'Clinical Psychologist',
            ],
            [
                'job_title'                  => 'Dietitian / Nutritionist',
                'institution_name'           => 'City Hospital',
                'specialty_slug'             => 'dietetics-nutrition',
                'employment_type'            => 'contractual',
                'location_city'              => 'Indore',
                'location_state'             => 'Madhya Pradesh',
                'experience_min'             => 1,
                'experience_max'             => 4,
                'salary_min'                 => 250000,
                'salary_max'                 => 420000,
                'key_skills'                 => ['Nutrition Planning', 'Patient Counseling', 'Health Education'],
                'educational_requirements'   => ['B.Sc Nursing', 'Post Graduate Diploma'],
                'medical_qualifications'     => [],
                'certifications_required'    => ['Food Safety (FSSAI)', 'Diabetes Educator Certificate'],
                'description'                => 'Contractual Dietitian required for in-patient and out-patient nutrition counselling and therapeutic diet planning.',
                'vacancies'                  => 1,
                'is_featured'                => false,
                'category_slug'              => 'allied-health',
                'subcategory_name'           => 'Dietitian / Nutritionist',
            ],
            [
                'job_title'                  => 'Medical Records Officer',
                'institution_name'           => 'City Hospital',
                'specialty_slug'             => 'healthcare-administration',
                'employment_type'            => 'full_time',
                'location_city'              => 'Gurugram',
                'location_state'             => 'Haryana',
                'experience_min'             => 0,
                'experience_max'             => 2,
                'salary_min'                 => 250000,
                'salary_max'                 => 400000,
                'key_skills'                 => ['Medical Record Keeping', 'Electronic Health Records (EHR)', 'Medical Coding', 'Compliance & Regulatory'],
                'educational_requirements'   => ['10+2 (Science)', 'Certificate Course (Relevant)'],
                'medical_qualifications'     => [],
                'certifications_required'    => ['CPC (Certified Professional Coder)'],
                'description'                => 'Entry-level Medical Records Officer position. CPC / CCS certification preferred. Freshers with relevant training are welcome.',
                'vacancies'                  => 3,
                'is_featured'                => false,
                'category_slug'              => 'hospital-admin',
                'subcategory_name'           => 'Medical Records Officer',
            ],
            [
                'job_title'                  => 'Gastroenterologist',
                'institution_name'           => 'City Hospital',
                'specialty_slug'             => 'gastroenterology',
                'employment_type'            => 'full_time',
                'location_city'              => 'Bengaluru',
                'location_state'             => 'Karnataka',
                'experience_min'             => 5,
                'experience_max'             => 15,
                'salary_min'                 => 2000000,
                'salary_max'                 => 4000000,
                'key_skills'                 => ['Clinical Assessment', 'Patient Care', 'Medical Equipment Handling', 'Research & Data Analysis'],
                'educational_requirements'   => ['MBBS', 'MD', 'DM (Super Specialty)'],
                'medical_qualifications'     => ['MBBS', 'MD (Medicine)', 'DM (Gastroenterology)'],
                'certifications_required'    => ['Medical Council Registration (MCI/NMC)'],
                'description'                => 'Experienced Gastroenterologist required for our GI sciences department. Should be proficient in diagnostic and therapeutic endoscopy.',
                'vacancies'                  => 1,
                'is_featured'                => false,
                'category_slug'              => 'doctors',
                'subcategory_name'           => 'Gastroenterologist',
            ],
            [
                'job_title'                  => 'Consultant Anaesthesiologist',
                'institution_name'           => 'City Hospital',
                'specialty_slug'             => 'surgery-anaesthesiology',
                'employment_type'            => 'full_time',
                'location_city'              => 'Mumbai',
                'location_state'             => 'Maharashtra',
                'experience_min'             => 3,
                'experience_max'             => 10,
                'salary_min'                 => 1800000,
                'salary_max'                 => 3500000,
                'key_skills'                 => ['Anesthesia Administration', 'Critical Care', 'Operating Room Protocol', 'Ventilator Management'],
                'educational_requirements'   => ['MBBS', 'MD'],
                'medical_qualifications'     => ['MBBS', 'MD (Anesthesiology)'],
                'certifications_required'    => ['Medical Council Registration (MCI/NMC)', 'ACLS (Advanced Cardiac Life Support)'],
                'description'                => 'Consultant Anaesthesiologist required for a busy multi-specialty surgical centre. MD/DA Anaesthesiology with experience in regional blocks preferred.',
                'vacancies'                  => 2,
                'is_featured'                => false,
                'category_slug'              => 'doctors',
                'subcategory_name'           => 'Anesthesiologist',
            ],
            [
                'job_title'                  => 'OT Nurse',
                'institution_name'           => 'City Hospital',
                'specialty_slug'             => 'nursing-professionals',
                'employment_type'            => 'full_time',
                'location_city'              => 'New Delhi',
                'location_state'             => 'Delhi',
                'experience_min'             => 1,
                'experience_max'             => 5,
                'salary_min'                 => 350000,
                'salary_max'                 => 600000,
                'key_skills'                 => ['Operating Room Protocol', 'Infection Control', 'Surgical Assistance', 'Medical Equipment Handling'],
                'educational_requirements'   => ['B.Sc Nursing', 'GNM (General Nursing & Midwifery)'],
                'medical_qualifications'     => ['B.Sc Nursing'],
                'certifications_required'    => ['Nursing Council Registration', 'OT Technician Certificate', 'Infection Control Certificate'],
                'description'                => 'OT Nurse required for our surgical department. Must have experience assisting in major surgical procedures.',
                'vacancies'                  => 3,
                'is_featured'                => false,
                'category_slug'              => 'nursing',
                'subcategory_name'           => 'Operation Theatre Nurse',
            ],
            [
                'job_title'                  => 'Nephrologist',
                'institution_name'           => 'City Hospital',
                'specialty_slug'             => 'nephrology-urology',
                'employment_type'            => 'full_time',
                'location_city'              => 'Hyderabad',
                'location_state'             => 'Telangana',
                'experience_min'             => 4,
                'experience_max'             => 12,
                'salary_min'                 => 2000000,
                'salary_max'                 => 3800000,
                'key_skills'                 => ['Dialysis', 'Clinical Assessment', 'Patient Care', 'Critical Care'],
                'educational_requirements'   => ['MBBS', 'MD', 'DM (Super Specialty)'],
                'medical_qualifications'     => ['MBBS', 'MD (Medicine)', 'DM (Nephrology)'],
                'certifications_required'    => ['Medical Council Registration (MCI/NMC)', 'Dialysis Technician Certificate'],
                'description'                => 'Experienced Nephrologist needed for our renal sciences unit. DM Nephrology with dialysis experience is mandatory.',
                'vacancies'                  => 1,
                'is_featured'                => false,
                'category_slug'              => 'doctors',
                'subcategory_name'           => 'Nephrologist',
            ],
        ];

        foreach ($jobs as $data) {
            $specialtyId = $specialties[$data['specialty_slug']] ?? null;

            $approvedAt = now()->subDays(rand(1, 30));

            JobPosting::create([
                'recruiter_id'              => $recruiter->id,
                'job_title'                 => $data['job_title'],
                'job_description'           => $data['description'],
                'key_skills'                => $data['key_skills'],
                'educational_requirements'  => $data['educational_requirements'],
                'medical_qualifications'    => $data['medical_qualifications'],
                'certifications_required'   => $data['certifications_required'],
                'employment_type'           => $data['employment_type'],
                'experience_min'            => $data['experience_min'],
                'experience_max'            => $data['experience_max'],
                'location_city'             => $data['location_city'],
                'location_state'            => $data['location_state'],
                'salary_min'                => $data['salary_min'],
                'salary_max'                => $data['salary_max'],
                'salary_currency'           => 'INR',
                'salary_disclosed'          => true,
                'institution_name'          => $data['institution_name'],
                'number_of_vacancies'       => $data['vacancies'],
                'category_slug'             => $data['category_slug'],
                'subcategory_name'          => $data['subcategory_name'],
                'specialty_id'              => $specialtyId,
                'posting_duration_days'     => 60,
                'expires_at'                => now()->addDays(60),
                'admin_approved'            => true,
                'approved_at'               => $approvedAt,
                'is_active'                 => true,
                'is_featured'               => $data['is_featured'],
                'featured_at'               => $data['is_featured'] ? $approvedAt : null,
            ]);
        }

        $this->command->info('Seeded ' . count($jobs) . ' job postings.');
    }
}
