<?php

namespace Database\Seeders;

use App\Models\StandardTag;
use Illuminate\Database\Seeder;

class StandardTagSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            StandardTag::TYPE_KEY_SKILL => [
                'Patient Care',
                'Clinical Assessment',
                'Emergency Medicine',
                'Critical Care',
                'Surgical Assistance',
                'Pharmacology',
                'Medical Record Keeping',
                'Infection Control',
                'Vital Signs Monitoring',
                'Wound Management',
                'IV Administration',
                'Catheterization',
                'ECG Interpretation',
                'Ventilator Management',
                'CPR / BLS',
                'ACLS',
                'Phlebotomy',
                'Triage',
                'Health Education',
                'Patient Counseling',
                'Team Leadership',
                'Communication Skills',
                'Time Management',
                'Diagnostic Imaging',
                'Lab Analysis',
                'Electronic Health Records (EHR)',
                'Medical Coding',
                'Telemedicine',
                'Research & Data Analysis',
                'Quality Assurance',
                'Compliance & Regulatory',
                'Operating Room Protocol',
                'Anesthesia Administration',
                'Rehabilitation Therapy',
                'Mental Health Support',
                'Pediatric Care',
                'Geriatric Care',
                'Obstetric Care',
                'Dialysis',
                'Radiology',
                'Ultrasound',
                'MRI Interpretation',
                'Blood Bank Management',
                'Nutrition Planning',
                'Physiotherapy Techniques',
                'Occupational Therapy',
                'Speech Therapy',
                'Community Health Outreach',
                'Hospital Administration',
                'Medical Equipment Handling',
            ],

            StandardTag::TYPE_EDUCATIONAL_REQUIREMENT => [
                'MBBS',
                'MD',
                'MS (Surgery)',
                'BDS',
                'MDS',
                'BAMS',
                'BHMS',
                'BUMS',
                'B.Sc Nursing',
                'M.Sc Nursing',
                'GNM (General Nursing & Midwifery)',
                'ANM (Auxiliary Nursing & Midwifery)',
                'B.Pharm',
                'M.Pharm',
                'D.Pharm',
                'BPT (Physiotherapy)',
                'MPT (Physiotherapy)',
                'BOT (Occupational Therapy)',
                'B.Sc MLT (Medical Lab Technology)',
                'B.Sc Radiology',
                'B.Sc Optometry',
                'B.Sc Audiology & Speech',
                'BMLT',
                'DMLT',
                'MBA (Hospital Administration)',
                'MHA (Master of Hospital Administration)',
                'MPH (Master of Public Health)',
                'DNB',
                'DM (Super Specialty)',
                'MCh (Super Specialty)',
                'PhD (Medical Sciences)',
                'Post Graduate Diploma',
                '10+2 (Science)',
                'ITI (Relevant Trade)',
                'Diploma in Nursing',
                'Diploma in Pharmacy',
                'Diploma in Radiology',
                'Certificate Course (Relevant)',
            ],

            StandardTag::TYPE_MEDICAL_QUALIFICATION => [
                'MBBS',
                'MD (Medicine)',
                'MD (Pediatrics)',
                'MD (Radiology)',
                'MD (Anesthesiology)',
                'MD (Pathology)',
                'MD (Dermatology)',
                'MD (Psychiatry)',
                'MD (Ophthalmology)',
                'MD (Community Medicine)',
                'MS (General Surgery)',
                'MS (Orthopedics)',
                'MS (ENT)',
                'MS (Obstetrics & Gynecology)',
                'MS (Ophthalmology)',
                'DM (Cardiology)',
                'DM (Neurology)',
                'DM (Nephrology)',
                'DM (Gastroenterology)',
                'DM (Pulmonology)',
                'DM (Endocrinology)',
                'DM (Oncology)',
                'MCh (Neurosurgery)',
                'MCh (Cardiothoracic Surgery)',
                'MCh (Plastic Surgery)',
                'MCh (Urology)',
                'DNB (Various Specialties)',
                'FCPS',
                'FRCS',
                'MRCP',
                'BDS',
                'MDS (Orthodontics)',
                'MDS (Oral Surgery)',
                'BAMS',
                'BHMS',
                'BPT',
                'B.Sc Nursing',
                'M.Sc Nursing',
                'B.Pharm',
                'M.Pharm',
            ],

            StandardTag::TYPE_CERTIFICATION => [
                'BLS (Basic Life Support)',
                'ACLS (Advanced Cardiac Life Support)',
                'PALS (Pediatric Advanced Life Support)',
                'ATLS (Advanced Trauma Life Support)',
                'NRP (Neonatal Resuscitation Program)',
                'TNCC (Trauma Nursing Core Course)',
                'CPC (Certified Professional Coder)',
                'NABH Awareness',
                'ISO 9001 Auditor',
                'Infection Control Certificate',
                'Fire & Safety Certificate',
                'HAZMAT Certification',
                'Good Clinical Practice (GCP)',
                'Clinical Research Certification',
                'Phlebotomy Certification',
                'Dialysis Technician Certificate',
                'ECG Technician Certificate',
                'OT Technician Certificate',
                'Radiography License',
                'Pharmacy Council Registration',
                'Medical Council Registration (MCI/NMC)',
                'State Medical Council Registration',
                'Nursing Council Registration',
                'Dental Council Registration',
                'AYUSH Council Registration',
                'Food Safety (FSSAI)',
                'Biomedical Waste Management',
                'First Aid Certification',
                'Yoga Instructor Certification',
                'Diabetes Educator Certificate',
                'Critical Care Nursing Certificate',
                'Oncology Nursing Certificate',
                'Neonatal Nursing Certificate',
                'Midwifery Certification',
                'Hospital Management Certificate',
            ],
        ];

        foreach ($data as $type => $names) {
            foreach ($names as $index => $name) {
                StandardTag::updateOrCreate(
                    ['type' => $type, 'name' => $name],
                    ['sort_order' => $index + 1, 'is_active' => true]
                );
            }
        }
    }
}
